<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AgentDispatcher.Domain/AgentDispatcher.Domain.csproj" />
  </ItemGroup>
</Project>
